services:
  # Add nginx service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    command: /bin/bash -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - userservice
      - locationservice
      - reviewservice
    networks:
      - microservices-network

  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  userservice:
    build:
      context: ../backend/UserService
      dockerfile: Dockerfile
    # Using internal networking only, not exposing to host directly
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${USERSERVICE_CONNECTION_STRING}
      - Jwt__Key=${USERSERVICE_JWT_KEY}
      - Jwt__Issuer=${USERSERVICE_JWT_ISSUER}
      - Jwt__Audience=${USERSERVICE_JWT_AUDIENCE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
      
  reviewservice:
    build:
      context: ../backend/ReviewService
      dockerfile: Dockerfile
    # Using internal networking only, not exposing to host directly
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${REVIEWSERVICE_CONNECTION_STRING}
      - Jwt__Key=${REVIEWSERVICE_JWT_KEY}
      - Jwt__Issuer=${REVIEWSERVICE_JWT_ISSUER}
      - Jwt__Audience=${REVIEWSERVICE_JWT_AUDIENCE}
      - Services__LocationService__BaseUrl=http://locationservice:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network

  locationservice:
    build:
      context: ../backend/LocationService
      dockerfile: Dockerfile
    # Using internal networking only, not exposing to host directly
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=${LOCATIONSERVICE_CONNECTION_STRING}
      - Jwt__Key=${LOCATIONSERVICE_JWT_KEY}
      - Jwt__Issuer=${LOCATIONSERVICE_JWT_ISSUER}
      - Jwt__Audience=${LOCATIONSERVICE_JWT_AUDIENCE}
      - Services__Url=http://locationservice:8080/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data:
